# Generated by Django 5.1.7 on 2025-04-03 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ethereumaccount',
            old_name='address',
            new_name='eth_address',
        ),
        migrations.RenameField(
            model_name='ethereumaccount',
            old_name='private_key',
            new_name='eth_private_key',
        ),
    ]
